server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${PROMTAIL_CLIENT_PUSH_URL}

scrape_configs:
  - job_name: push
    loki_push_api:
      server:
        http_listen_port: ${PROMTAIL_PORT}
        grpc_listen_port: 0