global:
  scrape_interval: 60s
  evaluation_interval: 60s


scrape_configs:
  - job_name: 'microservice_1'
    honor_labels: true
    metrics_path: '/actuator/prometheus'
    params:
      'match[]':
        - '{__name__=~".+"}'
    static_configs:
      - targets: ['microservice_1_URL:PORT']
        labels:
          team: 'team'
          application: 'application'

  - job_name: 'microservice_2'
    honor_labels: true
    params:
      'match[]':
        - '{__name__=~".+"}'
    static_configs:
      - targets: ['microservice_1_URL:PORT2']
        labels:
          team: 'team'
          application: 'application'
